export const GET_CATEGORY = "GET_CATEGORY";
export const GET_LIST_CATEGORY = "GET_LIST_CATEGORY";

export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS";
export const SET_LIST_CATEGORY_SUCCESS = "SET_LIST_CATEGORY_SUCCESS";
export const POST_CATEGORY = 'POST_CATEGORY';
export const PUT_CATEGORY = 'PUT_CATEGORY';
export const SET_CATEGORY_SUCCESS = 'SET_CATEGORY_SUCCESS';

export const SEARCH_CATEGORY = 'SEARCH_CATEGORY';
export const SEARCH_CATEGORY_SUCCESS = 'SEARCH_CATEGORY_SUCCESS';
