export const GET_DEPARTMENT = "GET_DEPARTMENT";
export const SET_DEPARTMENT = "SET_DEPARTMENT";

export const GET_LIST_DEPARTMENT = "GET_LIST_DEPARTMENT";
export const SET_LIST_DEPARTMENT = "SET_LIST_DEPARTMENT";

export const CREATE_DEPARTMENT = "CREATE_DEPARTMENT";

export const UPDATE_DEPARTMENT = "UPDATE_DEPARTMENT";
