/**
 * GET
 */
export const GET_REQUEST = "GET_REQUEST";
export const SET_REQUEST_SUCCESS = "SET_REQUEST_SUCCESS";

export const GET_REQUEST_BY_ID = "GET_REQUEST_BY_ID";
export const SET_REQUEST_BY_ID_SUCCESS = "SET_REQUEST_BY_ID_SUCCESS";

export const GET_REQUEST_BY_FILTER = "GET_REQUEST_BY_FILTER";
export const SET_REQUEST_BY_FILTER_SUCCESS = "SET_REQUEST_BY_FILTER_SUCCESS";
/**
 * CREATE
 */
export const CREATE_REQUEST = "CREATE_REQUEST";
/**
 * DELETE
 */
export const DELETE_REQUEST = "DELETE_REQUEST";
/**
 * UPDATE
 */
export const UPDATE_REQUEST = "UPDATE_REQUEST";
/**
 * CREATE_COMMENT
 */
export const CREATE_COMMENT = "CREATE_COMMENT";
/**
 * LIST_COMMENT
 */
export const GET_LIST_COMMENT = "GET_LIST_COMMENT";
export const SET_LIST_COMMENT_SUCCESS = "SET_LIST_COMMENT_SUCCESS";
/**
 * HISTORY
 */
export const GET_HISTORY_REQUEST = "GET_HISTORY_REQUEST";
export const SET_HISTORY_REQUEST_SUCCESS = "SET_HISTORY_REQUEST_SUCCESS";
