export const GET_LIST_USER = "GET_LIST_USER";
export const SET_LIST_USER_SUCCESS = "SET_LIST_USER_SUCCESS";

export const GET_LIST_ASSIGNEE = "GET_LIST_ASSIGNEE";
export const SET_LIST_ASSIGNEE_SUCCESS = "SET_LIST_ASSIGNEE_SUCCESS";

export const GET_USER = "GET_USER";
export const SET_USER_SUCCESS = "SET_USER_SUCCESS";

export const SEARCH_USER = "SEARCH_USER";
export const SEARCH_USER_SUCCESS = "SEARCH_USER_SUCCESS";

export const POST_USER = "POST_USER";
export const PUT_USER = "PUT_USER";

export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const SET_CURRENT_USER_SUCCESS = "SET_CURRENT_USER_SUCCESS";
